workflow "Publish on Netlify" {
  on = "push"
  resolves = ["Publish"]
}

action "Publish" {
  uses = "netlify/actions/build@master"
  secrets = ["GITHUB_TOKEN"]
  env = {
    NETLIFY_BASE = "site"
    NETLIFY_CMD = "npm build"
    NETLIFY_DIR = "site/_build"
  }
}
